#!/usr/bin/env python
"""Do two judges from different families fail *independently*? (SPEC.md §24.3,
§10.5; ADR-087)

    .venv/bin/python scripts/judge_entanglement.py --judges llama3.2,qwen2.5 [--json out.json]
    .venv/bin/python scripts/judge_entanglement.py --selftest

Why this exists. `concreteness.py` refuses a judge from the generator's family,
because §24.3 routes criticism to "a different provider/family" -- and §10.5
leans harder on the same idea: an estimated-negative-EV death needs "an
independent Auditor or evaluator" to concur. Both treat *different family* as
if it meant *independent*. Recent work says it often does not: "How Independent
are Large Language Models?" (arXiv 2604.07650) finds widespread behavioural
entanglement across 18 models from six families -- shared pretraining data,
distillation and alignment pipelines produce synchronised failures, so two
judges agreeing can be one error counted twice -- and "Artificial Hivemind"
(NeurIPS 2025) finds different models' open-ended outputs strikingly
homogeneous. Neither measured *this* instrument. This does.

## What it measures

Every judge scores the same hand-labelled fixture `concreteness.py --selftest`
uses, with the same prompt, the same temperature-0 call and the same
deterministic quote check, so a verdict here is exactly the verdict the
instrument would give. Then, per pair of judges:

- **Error rates** against the human labels, and how many cases **both** got
  wrong, next to the number expected if their errors were independent
  (`n * p_a * p_b`). More joint errors than that is entanglement.
- **phi** -- the correlation of the two judges' *error indicators*. 0 means
  their mistakes are unrelated; positive means they fail on the same cases.
- **P(B wrong | A wrong)** against **P(B wrong)**: the operational question
  §10.5 asks. If a second judge is more likely to be wrong exactly when the
  first one is, its concurrence is worth less than it looks.
- **False concurrence**: cases where both judges called an empty proposal
  concrete. That is the §10.5 failure itself -- two "independent" judges
  agreeing on something that is not there -- and the one number here that
  should be zero.

## When the correlation is an artifact

Two shapes make `phi` meaningless, and the script checks for both before
printing it. A **constant judge** -- one returning the same verdict for every
case -- has errors equal to the label base rate, so any correlation with it
describes the fixture, not the judge. And when **both judges only ever err in
the same direction** (both miss deliverables, neither invents one), their
errors can only fall inside the same labelled class, so they must overlap
beyond independence whatever the models share. Both are reported as warnings
beside the number. The first live run hit both (ADR-087): `llama3.2` scored all
24 proposals empty.

## What it does not claim

Twenty-four cases is a small sample; the counts are printed, not just the
ratios, so the reader can see how few joint errors a phi is built from. And the
fixture was written by `llama3.2` arms, so a `llama3.2` judge is grading its own
family's proposals -- reported as a stamp on its row, never hidden, because it
confounds that judge's error rate (not the entanglement arithmetic).

Imports nothing from `mitosis`, like the scripts it sits next to.
"""
from __future__ import annotations

import argparse
import itertools
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import concreteness  # noqa: E402

#: The arms the fixture's proposals came from (`concreteness_fixture.json`'s
#: `arm` field), all generated by this model.
FIXTURE_GENERATOR = "llama3.2"


# -------------------------------------------------------------------- the maths

def phi(x: list[bool], y: list[bool]) -> float | None:
    """Pearson correlation of two binary vectors (the phi coefficient); `None`
    when either is constant, where correlation is undefined."""
    n = len(x)
    a = sum(1 for i in range(n) if x[i] and y[i])
    b = sum(1 for i in range(n) if x[i] and not y[i])
    c = sum(1 for i in range(n) if not x[i] and y[i])
    d = n - a - b - c
    denom = math.sqrt((a + b) * (c + d) * (a + c) * (b + d))
    return (a * d - b * c) / denom if denom else None


def cohen_kappa(x: list[bool], y: list[bool]) -> float | None:
    """Agreement between two judges' verdicts beyond what their base rates
    alone would produce; `None` when chance agreement is total."""
    n = len(x)
    observed = sum(1 for i in range(n) if x[i] == y[i]) / n
    px, py = sum(x) / n, sum(y) / n
    expected = px * py + (1 - px) * (1 - py)
    return (observed - expected) / (1 - expected) if expected < 1 else None


def pair_report(labels: list[bool], verdicts_a: list[bool], verdicts_b: list[bool]) -> dict:
    n = len(labels)
    err_a = [verdicts_a[i] != labels[i] for i in range(n)]
    err_b = [verdicts_b[i] != labels[i] for i in range(n)]
    p_a, p_b = sum(err_a) / n, sum(err_b) / n
    both_wrong = sum(1 for i in range(n) if err_a[i] and err_b[i])
    fn_a = sum(1 for i in range(n) if labels[i] and not verdicts_a[i])
    fn_b = sum(1 for i in range(n) if labels[i] and not verdicts_b[i])
    fp_a, fp_b = sum(err_a) - fn_a, sum(err_b) - fn_b
    return {
        "n": n,
        "a_constant": len(set(verdicts_a)) == 1,
        "b_constant": len(set(verdicts_b)) == 1,
        "false_negatives_a": fn_a, "false_positives_a": fp_a,
        "false_negatives_b": fn_b, "false_positives_b": fp_b,
        # Every error of both judges in one shared direction: the overlap
        # beyond independence is then forced by the labels, not measured.
        "one_directional": (fp_a == 0 and fp_b == 0) or (fn_a == 0 and fn_b == 0),
        "errors_a": sum(err_a),
        "errors_b": sum(err_b),
        "both_wrong": both_wrong,
        "both_wrong_if_independent": round(n * p_a * p_b, 3),
        "error_phi": phi(err_a, err_b),
        "p_b_wrong": round(p_b, 3),
        "p_b_wrong_given_a_wrong": round(both_wrong / sum(err_a), 3) if sum(err_a) else None,
        "verdict_kappa": cohen_kappa(verdicts_a, verdicts_b),
        "false_concurrence": sum(
            1 for i in range(n) if not labels[i] and verdicts_a[i] and verdicts_b[i]
        ),
    }


def selftest() -> int:
    failures = 0

    def check(label, got, expected):
        nonlocal failures
        ok = (got is None and expected is None) or (
            got is not None and expected is not None and abs(got - expected) < 1e-9)
        failures += not ok
        print(f"  [{'ok' if ok else 'FAIL'}] {label}: {got} expected {expected}")

    t, f = True, False
    check("phi of identical vectors", phi([t, f, t, f], [t, f, t, f]), 1.0)
    check("phi of complementary vectors", phi([t, f, t, f], [f, t, f, t]), -1.0)
    check("phi of unrelated vectors", phi([t, t, f, f], [t, f, t, f]), 0.0)
    check("phi with a constant vector is undefined", phi([t, t, t, t], [t, f, t, f]), None)
    check("kappa of identical verdicts", cohen_kappa([t, f, t, f], [t, f, t, f]), 1.0)
    check("kappa of chance-level verdicts", cohen_kappa([t, t, f, f], [t, f, t, f]), 0.0)
    report = pair_report([t, f, t, f], [f, t, t, f], [f, t, t, f])
    check("two judges wrong on the same two cases: both_wrong", report["both_wrong"], 2)
    check("... expected if independent", report["both_wrong_if_independent"], 1.0)
    check("... one of them a false concurrence", report["false_concurrence"], 1)
    constant = pair_report([t, f, t, f], [f, f, f, f], [f, f, t, f])
    check("a judge that always says empty is flagged constant", float(constant["a_constant"]), 1.0)
    check("two judges that only miss are one-directional", float(constant["one_directional"]), 1.0)
    check("errors in both directions are not", float(report["one_directional"]), 0.0)
    print("selftest:", "PASS" if not failures else f"{failures} FAILURE(S)")
    return 1 if failures else 0


# ------------------------------------------------------------------------ main

def score(judge: str, cases: list[dict], host: str) -> list[dict]:
    rows = []
    for case in cases:
        verdict, quote = concreteness.judge(case["summary"], host, judge)
        rows.append({"summary": case["summary"], "label": case["concrete"],
                     "verdict": verdict, "concrete": verdict == "concrete", "quote": quote})
        mark = "ok" if (verdict == "concrete") == case["concrete"] else "!!"
        print(f"  [{mark}] {judge:10s} {verdict:10s} {case['summary'][:60]}", flush=True)
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--judges", default="llama3.2,qwen2.5",
                    help="comma-separated judge models, at least two")
    ap.add_argument("--host", default=concreteness.DEFAULT_HOST)
    ap.add_argument("--selftest", action="store_true", help="check the maths; needs no model")
    ap.add_argument("--json", help="write every verdict and pair report here")
    ap.add_argument("--from-json", help="re-analyse verdicts a previous --json run saved, "
                                        "without querying any model")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    with open(concreteness.FIXTURE) as fh:
        cases = json.load(fh)
    labels = [c["concrete"] for c in cases]

    if args.from_json:
        with open(args.from_json) as fh:
            saved = json.load(fh)
        judges, verdicts = saved["judges"], saved["verdicts"]
        if [r["summary"] for r in verdicts[judges[0]]] != [c["summary"] for c in cases]:
            ap.error("the saved verdicts are for a different fixture than the current one")
    else:
        judges = [j.strip() for j in args.judges.split(",") if j.strip()]
        if len(judges) < 2:
            ap.error("entanglement needs at least two judges")
        verdicts = {}
        for judge in judges:
            print(f"{judge}:", flush=True)
            verdicts[judge] = score(judge, cases, args.host)

    print(f"\n{len(cases)} hand-labelled proposals ({sum(labels)} concrete), "
          f"written by {FIXTURE_GENERATOR}")
    for judge in judges:
        wrong = sum(1 for r in verdicts[judge] if r["concrete"] != r["label"])
        stamp = ("  ** same family as the fixture's generator -- self-graded **"
                 if concreteness.family(judge) == concreteness.family(FIXTURE_GENERATOR) else "")
        print(f"  {judge:12s} errors {wrong}/{len(cases)}{stamp}")

    pairs = {}
    for a, b in itertools.combinations(judges, 2):
        report = pair_report(labels, [r["concrete"] for r in verdicts[a]],
                             [r["concrete"] for r in verdicts[b]])
        pairs[f"{a}|{b}"] = report
        fmt = lambda v: "undefined" if v is None else f"{v:+.3f}"  # noqa: E731
        print(f"\n{a} vs {b}")
        print(f"  both wrong             {report['both_wrong']}  "
              f"(expected {report['both_wrong_if_independent']} if independent)")
        print(f"  error phi              {fmt(report['error_phi'])}")
        print(f"  P({b} wrong)          {report['p_b_wrong']}")
        print(f"  P({b} wrong | {a} wrong)  {report['p_b_wrong_given_a_wrong']}")
        print(f"  verdict kappa          {fmt(report['verdict_kappa'])}")
        print(f"  false concurrence      {report['false_concurrence']}  "
              "(both called an empty proposal concrete)")
        print(f"  error directions       {a}: {report['false_negatives_a']} missed / "
              f"{report['false_positives_a']} invented; {b}: {report['false_negatives_b']} missed / "
              f"{report['false_positives_b']} invented")
        for name, constant in ((a, report["a_constant"]), (b, report["b_constant"])):
            if constant:
                print(f"  WARNING: {name} returned one verdict for every case -- its errors are the "
                      "label base rate, and phi against it describes the fixture, not the judge")
        if report["one_directional"]:
            print("  WARNING: both judges err in one direction only, so their errors must overlap "
                  "inside one labelled class -- the excess joint errors above are forced, "
                  "not evidence of shared failure modes")

    if args.json:
        with open(args.json, "w") as fh:
            json.dump({"judges": judges, "fixture_generator": FIXTURE_GENERATOR,
                       "verdicts": verdicts, "pairs": pairs}, fh, indent=2)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
